# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#1_about'
    weight: 1
  - name: Posts
    url: '#4_recent_posts'
    weight: 2
  - name: Projects
    url: '#5_projects'
    weight: 3
  - name: Contact
    url: '#8_contact'
    weight: 4
  - name: CV
    url: uploads/Lorcan Nicholls - CV.pdf
    weight: 5
